#!/usr/bin/env bun
// Codegen for the self-contained binary: reads migrations (app/drizzle),
// seed SOULs (agents/) and the SPA build (dashboard/dist) from disk and
// generates app/src/embedded-assets.generated.ts with INLINE content (plain
// text for migrations/SOULs, base64 for the SPA) — avoids depending on
// `import ... with { type: "file" }` in `bun build --compile` for a dynamic
// file tree (the SPA has hashed filenames, regenerated on every build).
//
// Run by the release pipeline BEFORE `bun build --compile` (never in
// dev/Docker — there the empty placeholder committed to git is enough, see
// the generated file itself). Idempotent: safe to run again at any time.
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative, resolve, sep } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const DRIZZLE_DIR = resolve(ROOT, "drizzle");
const AGENTS_DIR = resolve(ROOT, "..", "agents");
const DASHBOARD_DIST = resolve(ROOT, "..", "dashboard", "dist");
const OUT_FILE = resolve(ROOT, "src", "embedded-assets.generated.ts");

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".map": "application/json; charset=utf-8",
};

function contentType(path: string): string {
  return CONTENT_TYPES[extname(path).toLowerCase()] ?? "application/octet-stream";
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function loadMigrations(): { migrations: Record<string, string>; journal: string | null } {
  if (!existsSync(DRIZZLE_DIR)) return { migrations: {}, journal: null };
  const migrations: Record<string, string> = {};
  for (const file of readdirSync(DRIZZLE_DIR)) {
    if (file.endsWith(".sql")) migrations[file.replace(/\.sql$/, "")] = readFileSync(join(DRIZZLE_DIR, file), "utf8");
  }
  const journalPath = join(DRIZZLE_DIR, "meta", "_journal.json");
  const journal = existsSync(journalPath) ? readFileSync(journalPath, "utf8") : null;
  return { migrations, journal };
}

function loadSouls(): { souls: Record<string, string>; protocol: string | null } {
  if (!existsSync(AGENTS_DIR)) return { souls: {}, protocol: null };
  const souls: Record<string, string> = {};
  for (const file of readdirSync(AGENTS_DIR)) {
    if (file.endsWith(".SOUL.md")) souls[file] = readFileSync(join(AGENTS_DIR, file), "utf8");
  }
  const protocolPath = join(AGENTS_DIR, "COMMUNICATION_PROTOCOL.md");
  const protocol = existsSync(protocolPath) ? readFileSync(protocolPath, "utf8") : null;
  return { souls, protocol };
}

function loadDashboardAssets(): Record<string, { base64: string; contentType: string }> {
  if (!existsSync(DASHBOARD_DIST)) return {};
  const assets: Record<string, { base64: string; contentType: string }> = {};
  for (const file of walk(DASHBOARD_DIST)) {
    const rel = relative(DASHBOARD_DIST, file).split(sep).join("/");
    assets[rel] = { base64: readFileSync(file).toString("base64"), contentType: contentType(file) };
  }
  return assets;
}

function main(): void {
  const { migrations, journal } = loadMigrations();
  const { souls, protocol } = loadSouls();
  const dashboardAssets = loadDashboardAssets();

  if (Object.keys(migrations).length === 0) {
    console.warn(`⚠️  no migrations found in ${DRIZZLE_DIR} — the compiled binary would ship without a schema.`);
  }
  if (Object.keys(dashboardAssets).length === 0) {
    console.warn(`⚠️  ${DASHBOARD_DIST} does not exist or is empty — run "bun run build" in dashboard/ first (the SPA will not be embedded).`);
  }

  const body = `// GENERATED by scripts/generate-embedded-assets.ts at ${new Date().toISOString()} — do NOT hand-edit.
export interface EmbeddedFile {
  base64: string;
  contentType: string;
}

export const EMBEDDED_MIGRATIONS: Record<string, string> = ${JSON.stringify(migrations, null, 2)};
export const EMBEDDED_MIGRATIONS_JOURNAL: string | null = ${journal ? JSON.stringify(journal) : "null"};

export const EMBEDDED_SOULS: Record<string, string> = ${JSON.stringify(souls, null, 2)};
export const EMBEDDED_COMMUNICATION_PROTOCOL: string | null = ${protocol ? JSON.stringify(protocol) : "null"};

export const EMBEDDED_DASHBOARD_ASSETS: Record<string, EmbeddedFile> = ${JSON.stringify(dashboardAssets, null, 2)};
`;

  writeFileSync(OUT_FILE, body);
  console.log(
    `✅ ${OUT_FILE}: ${Object.keys(migrations).length} migration(s), ${Object.keys(souls).length} SOUL(s), ${
      Object.keys(dashboardAssets).length
    } SPA asset(s).`
  );
}

main();
